[package]
name = "suricata-lua-sys"
description = "Vendored Lua for Suricata"
version = "0.1.0-alpha.1"
edition = "2021"
rust-version = "1.56.0"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
